site_name: Moje projekty
site_author: Rafa Benderz
site_url: https://github.com/Rafal-codeBenderz.github.io/ds_ai_portfolio
site_description: >-
    Portfolio moich wspaniaych projekt贸w z Data Science i AI!
repo_name: Rafal-codeBenderz/ds_ai_portfolio
repo_url: https://github.com/Rafal-codeBenderz/ds_ai_portfolio

theme:
  name: material
  palette:
    primary: blue

nav:
  -  Start: index.md
  -  Analizy:    
     -  Titanic (analiza prze偶ywalnoci): Analizy/Titanic/index.md
     -  Iris (klasyfikacja kwiat贸w): Analizy/Iris/index.md
  -  Aplikacje:
      -  P贸maraton: Aplikacje/Maraton/index.md
      -  P贸maraton2: Aplikacje/Maraton2/index.md 
      -  Kolorowanka_Fantazja: Aplikacje/Kolorowanka_Fantazja/index.md 