site_name: Moje projekty
site_author: RafaÅ‚ Benderz
site_description: >
  Portfolio moich projektÃ³w z Data Science i AI!

repo_name: Rafal-codeBenderz/ds_ai_portfolio
repo_url: https://github.com/Rafal-codeBenderz/ds_ai_portfolio.git

theme:
  name: material
  palette:
    primary: blue

nav:
  - ğŸ  Start: index.md
  - ğŸ“Š Analizy:    
     -  Titanic (analiza przeÅ¼ywalnoÅ›ci): Analizy/Titanic/index.md
     -  Iris (klasyfikacja kwiatÃ³w): Analizy/Iris/index.md
  - ğŸ’» Aplikacje: 
      -  PÃ³Å‚maraton: Aplikacje/Maraton/index.md
      -  Kolorowanka: Aplikacje/Kolorowanka/index.md