site_name: Moje projekty
site_author: RafaÅ‚ Benderz
site_url: https://Rafal-codeBenderz.github.io/ds_ai_portfolio
site_description: >-
    Portfolio moich wspaniaÅ‚ych projektÃ³w z Data Science i AI!
repo_name: Rafal-codeBenderz/ds_ai_portfolio
repo_url: https://github.com/Rafal-codeBenderz/ds_ai_portfolio

theme:
  name: material
  palette:
    primary: blue

nav:
  - ğŸ  Start: index.md
  - ğŸ“Š Analizy: 
     -  Iris: Analizy/Iris/index.md   
     -  Titanic: Analizy/Titanic/index.md
  - ğŸ’» Aplikacje: 
      -  PÃ³Å‚maraton: Aplikacje/Maraton/index.md
      -  Kolorowanka_Fantazja: Aplikacje/Kolorowanka_Fantazja/index.md